# Generated by Django 4.2.11 on 2025-07-20 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import fininfo.utils.validators
import imagekit.models.fields
import parler.fields
import parler.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratildi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirildi")),
                ('news_status', models.CharField(choices=[('published', 'Chop etildi'), ('draft', 'Qoralama')], default='published', max_length=20, verbose_name='Holati')),
                ('publish', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Sana')),
                ('number_of_views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Muhim yangilik')),
                ('author_choice', models.BooleanField(default=False, verbose_name='Muharrir tanlovi')),
                ('youtube_link', models.CharField(blank=True, max_length=255, verbose_name='Youtube video')),
                ('tizer_id', models.CharField(blank=True, help_text='Telegram kanalga video xabar joylash uchun maxsus kanalga                 joylangan video havolasini kiriting', max_length=255, validators=[fininfo.utils.validators.validate_telegram_link], verbose_name='Tizer')),
                ('image', models.ImageField(max_length=500, upload_to='images/', verbose_name='Asosiy rasm')),
                ('short_slug', models.SlugField(max_length=10, unique=True)),
                ('expired_at', models.DateTimeField(null=True, verbose_name='Amal qilish muddati')),
                ('send_tg', models.BooleanField(default=True, verbose_name='Telegramdan yuborish')),
                ('is_sent_tg', models.BooleanField(default=False, verbose_name='Telegramdan yuborildi')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NewsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratildi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirildi")),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='gallery/', verbose_name='Rasm')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='news.news')),
            ],
            options={
                'verbose_name': 'Foto galereya',
                'verbose_name_plural': 'Foto galereya',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratildi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirildi")),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Sarlavha')),
                ('short_content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Qisqa matn (Lid)')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Kontent')),
                ('image_source', models.CharField(blank=True, max_length=255, verbose_name='Asosiy rasm ostidagi yozuv')),
                ('image_name', models.CharField(blank=True, help_text="Google'da izlaganda joylangan asosiy rasmni topish oson                 bo'lishi uchun kalit so'zlar", max_length=255, verbose_name='Rasm nomi')),
                ('slug', models.SlugField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.news')),
                ('tags', taggit.managers.TaggableManager(help_text='Vergul bilan kiritilsin: (Misol: ekologiya, Aziz Abduhakimov)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Teg')),
            ],
            options={
                'verbose_name': 'Yangilik Translation',
                'db_table': 'news_news_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master'), ('slug', 'language_code')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
