version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}
  production_django_staticfiles: {}

services:
  django: &django
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: fininfo_django
    volumes:
      - production_django_media:/app/fininfo/media
      - production_django_staticfiles:/app/staticfiles
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: fininfo_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: fininfo_nginx
    ports:
      - 8020:80
    depends_on:
      - django
    volumes:
      - production_django_staticfiles:/usr/share/nginx/staticfiles:ro
      - production_django_media:/usr/share/nginx/media:ro

  redis:
    restart: unless-stopped
    image: docker.io/redis:6

  celeryworker:
    <<: *django
    image: fininfo_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: fininfo_celerybeat
    command: /start-celerybeat
