# Generated by Django 4.2.11 on 2025-07-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratildi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirildi")),
                ('name', models.CharField(max_length=256, verbose_name='Nomi')),
                ('image', models.ImageField(upload_to='ads', verbose_name='Rasm')),
                ('link', models.URLField(max_length=512, verbose_name='Havola')),
                ('max_views', models.IntegerField(blank=True, null=True, verbose_name="Maksimal ko'rishlar soni")),
                ('max_clicks', models.IntegerField(blank=True, null=True, verbose_name='Maksimak bosishlar soni')),
                ('is_active', models.BooleanField(default=False, verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
            },
        ),
        migrations.CreateModel(
            name='AdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratildi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirildi")),
                ('name', models.CharField(max_length=256, verbose_name='Nomi')),
                ('width', models.SmallIntegerField(verbose_name='Rasm eni')),
                ('height', models.SmallIntegerField(verbose_name='Rasm balandligi')),
                ('slug', models.SlugField(max_length=256, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Reklama turi',
                'verbose_name_plural': 'Reklamalar turi',
            },
        ),
        migrations.CreateModel(
            name='AdStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratildi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirildi")),
                ('stat_type', models.CharField(choices=[('views', "Ko'rishlar"), ('clicks', 'Bosishlar')], max_length=10, verbose_name='Statistika turi')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_stat', to='ads.ad', verbose_name='Reklama')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistika',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='ads.adtype', verbose_name='Reklama turi'),
        ),
    ]
